name: M4 monthly ESRNN Experiment
dataset_name: m4monthly
architecture: residual lstm
device: cpu #cuda
train_parameters:
  max_epochs: 10
  batch_size: 1
  freq_of_test: 1
  learning_rate: 5e-4
  lr_scheduler_step_size: 12
  per_series_lr_multip: 1.0
  gradient_eps: 1e-6
  gradient_clipping_threshold: 20
  rnn_weight_decay: 0
  noise_std: 0.001
  level_variability_penalty: 50
  percentile: 50
  training_percentile: 49
data_parameters:
  seasonality: 12
  input_size: 12
  output_size: 18
  exogenous_size: 6
  min_inp_seq_length: 0
  data_dir: "./data/m4/"
  output_dir: "./results/m4/"
  max_num_series: 100
model_parameters:
  state_hsize: 50
  lback: 0
  dilations: [[1, 3], [6, 12]]
  add_nl_layer: FALSE
  averaging_level: 5
