name: M4 daily ESRNN Experiment
dataset_name: m4daily
architecture: residual lstm
device: cpu #cuda
train_parameters:
  max_epochs: 15
  batch_size: 1
  freq_of_test: 1
  learning_rate: 3e-4
  lr_scheduler_step_size: 9
  per_series_lr_multip: 1.5
  gradient_eps: 1e-6
  gradient_clipping_threshold: 20
  rnn_weight_decay: 0
  noise_std: 0.001
  level_variability_penalty: 100
  percentile: 50
  training_percentile: 49
data_parameters:
  seasonality: 7
  input_size: 7
  output_size: 14
  exogenous_size: 6
  min_inp_seq_length: 0
  data_dir: "./data/m4/"
  output_dir: "./results/m4/"
  max_num_series: 100
model_parameters:
  state_hsize: 40
  lback: 0
  dilations: [[1, 7], [28]]
  add_nl_layer: TRUE
  averaging_level: 5
